/**
 * Drop-in replacement for @anthropic-ai/claude-agent-sdk with multi-provider support.
 *
 * Usage:
 *   import { query, tool, createSdkMcpServer } from "one-agent-sdk/claude-agent-sdk";
 *
 * 100% API-compatible with @anthropic-ai/claude-agent-sdk.
 * Pass `options.provider` to route to a different backend (codex, kimi-cli, or custom).
 * Defaults to claude-code when no provider is specified.
 *
 * Types and lightweight functions are our own — no dependency on the Anthropic SDK
 * for type checking. The real SDK is only needed at runtime for the claude-code provider.
 */

// Functions — delegated to real SDK at runtime
export {
  getSessionMessages,
  listSessions,
  unstable_v2_createSession,
  unstable_v2_prompt,
  unstable_v2_resumeSession,
} from "./delegates.js";
export { createSdkMcpServer } from "./mcp-server.js";
export { query } from "./query.js";
// Functions — our own implementations
export { tool } from "./tool.js";
// Types
export type {
  AbortError,
  AccountInfo,
  AgentDefinition,
  AgentInfo,
  AgentMcpServerSpec,
  AnyZodRawShape,
  ApiKeySource,
  AsyncHookJSONOutput,
  BaseHookInput,
  BaseOutputFormat,
  BetaMessage,
  BetaRawMessageStreamEvent,
  BetaUsage,
  CallToolResult,
  CanUseTool,
  ConfigChangeHookInput,
  ConfigScope,
  ContentBlock,
  CreateSdkMcpServerOptions,
  ElicitationHookInput,
  ElicitationHookSpecificOutput,
  ElicitationRequest,
  ElicitationResult,
  ElicitationResultHookInput,
  ElicitationResultHookSpecificOutput,
  ExitReason,
  FastModeState,
  GetSessionMessagesOptions,
  HookCallback,
  HookCallbackMatcher,
  HookEvent,
  HookInput,
  HookJSONOutput,
  InferShape,
  InstructionsLoadedHookInput,
  JsonSchemaOutputFormat,
  ListSessionsOptions,
  McpClaudeAIProxyServerConfig,
  McpHttpServerConfig,
  McpSdkServerConfig,
  McpSdkServerConfigWithInstance,
  McpServerConfig,
  McpServerConfigForProcessTransport,
  McpServerStatus,
  McpServerStatusConfig,
  McpSetServersResult,
  McpSSEServerConfig,
  McpStdioServerConfig,
  MessageParam,
  ModelInfo,
  ModelUsage,
  NonNullableUsage,
  NotificationHookInput,
  NotificationHookSpecificOutput,
  OnElicitation,
  Options,
  OutputFormat,
  OutputFormatType,
  PermissionBehavior,
  PermissionMode,
  PermissionRequestHookInput,
  PermissionRequestHookSpecificOutput,
  PermissionResult,
  PermissionRuleValue,
  PermissionUpdate,
  PermissionUpdateDestination,
  PostToolUseFailureHookInput,
  PostToolUseFailureHookSpecificOutput,
  PostToolUseHookInput,
  PostToolUseHookSpecificOutput,
  PreCompactHookInput,
  PreToolUseHookInput,
  PreToolUseHookSpecificOutput,
  PromptRequest,
  PromptRequestOption,
  PromptResponse,
  Query,
  RewindFilesResult,
  SandboxFilesystemConfig,
  SandboxIgnoreViolations,
  SandboxNetworkConfig,
  SandboxSettings,
  SDKAssistantMessage,
  SDKAssistantMessageError,
  SDKAuthStatusMessage,
  SDKCompactBoundaryMessage,
  SDKControlInitializeResponse,
  SDKElicitationCompleteMessage,
  SDKFilesPersistedEvent,
  SDKHookProgressMessage,
  SDKHookResponseMessage,
  SDKHookStartedMessage,
  SDKLocalCommandOutputMessage,
  SDKMessage,
  SDKPartialAssistantMessage,
  SDKPermissionDenial,
  SDKPromptSuggestionMessage,
  SDKRateLimitEvent,
  SDKRateLimitInfo,
  SDKResultError,
  SDKResultMessage,
  SDKResultSuccess,
  SDKSession,
  SDKSessionInfo,
  SDKSessionOptions,
  SDKStatus,
  SDKStatusMessage,
  SDKSystemMessage,
  SDKTaskNotificationMessage,
  SDKTaskProgressMessage,
  SDKTaskStartedMessage,
  SDKToolProgressMessage,
  SDKToolUseSummaryMessage,
  SDKUserMessage,
  SDKUserMessageReplay,
  SdkBeta,
  SdkMcpToolDefinition,
  SdkPluginConfig,
  SessionEndHookInput,
  SessionMessage,
  SessionStartHookInput,
  SessionStartHookSpecificOutput,
  SettingSource,
  Settings,
  SetupHookInput,
  SetupHookSpecificOutput,
  SlashCommand,
  SpawnedProcess,
  SpawnOptions,
  StopHookInput,
  SubagentStartHookInput,
  SubagentStartHookSpecificOutput,
  SubagentStopHookInput,
  SyncHookJSONOutput,
  TaskCompletedHookInput,
  TeammateIdleHookInput,
  ThinkingAdaptive,
  ThinkingConfig,
  ThinkingDisabled,
  ThinkingEnabled,
  ToolAnnotations,
  ToolConfig,
  Transport,
  UserPromptSubmitHookInput,
  UserPromptSubmitHookSpecificOutput,
  WorktreeCreateHookInput,
  WorktreeRemoveHookInput,
  ZodRawShape,
} from "./types.js";
// Constants
export { EXIT_REASONS, HOOK_EVENTS } from "./types.js";
